import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generatePackSourceChangeFile, type GeneratePackSourceChangeFileOptions, type PackPromotionFileFailure } from "../packs/pack-draft-promotion-file.ts";
import { sha256 } from "../packs/pack-draft-promotion.ts";
export const GENERATE_PACK_SOURCE_CHANGE_USAGE = "Usage: npx tsx src/scripts/generate-pack-source-change.ts --repository-root <path> --workspace-root <path> --request <json> --proposal <json> --authorization <json> --plan <json> --patch-output <patch> --receipt-output <json> [--packs-after-output <json>]";
const REQUIRED = ["--repository-root", "--workspace-root", "--request", "--proposal", "--authorization", "--plan", "--patch-output", "--receipt-output"] as const; const OPTIONAL = ["--packs-after-output"] as const; const ALL = [...REQUIRED, ...OPTIONAL] as const; type Flag = (typeof ALL)[number];
function invalid(detail: string): PackPromotionFileFailure { return Object.freeze({ ok: false, reason: "invalid_arguments", detail }); }
export function parseGeneratePackSourceChangeArguments(argv: readonly string[]): { readonly ok: true; readonly options: GeneratePackSourceChangeFileOptions } | PackPromotionFileFailure {
  const values = new Map<Flag, string>(); const supplied = argv.slice(2);
  for (let i = 0; i < supplied.length; i += 1) { const token = supplied[i]; if (token === undefined) continue; if (!token.startsWith("--")) return invalid(`positional argument is not allowed: ${token}`); if (!ALL.includes(token as Flag)) return invalid(`unknown flag: ${token}`); const flag = token as Flag; if (values.has(flag)) return invalid(`duplicate flag: ${flag}`); const value = supplied[i + 1]; if (value === undefined || value.startsWith("--")) return invalid(`missing value for flag: ${flag}`); values.set(flag, value); i += 1; }
  const missing = REQUIRED.filter((flag) => !values.has(flag)); if (missing.length > 0) return invalid(`missing required flags: ${missing.join(", ")}`);
  return Object.freeze({ ok: true, options: Object.freeze({ repositoryRoot: values.get("--repository-root")!, workspaceRoot: values.get("--workspace-root")!, requestPath: values.get("--request")!, proposalPath: values.get("--proposal")!, authorizationPath: values.get("--authorization")!, planPath: values.get("--plan")!, patchOutputPath: values.get("--patch-output")!, receiptOutputPath: values.get("--receipt-output")!, ...(values.get("--packs-after-output") === undefined ? {} : { packsAfterOutputPath: values.get("--packs-after-output")! }) }) });
}
export async function main(argv: readonly string[] = process.argv, stdout: (text: string) => void = console.log, stderr: (text: string) => void = console.error, run: typeof generatePackSourceChangeFile = generatePackSourceChangeFile): Promise<number> { const parsed = parseGeneratePackSourceChangeArguments(argv); if (!parsed.ok) { stderr(JSON.stringify(parsed, null, 2)); stderr(GENERATE_PACK_SOURCE_CHANGE_USAGE); return 2; } const result = await run(parsed.options); if (!result.ok) { stderr(JSON.stringify(result, null, 2)); return 1; } stdout(JSON.stringify({ ok: true, patchSha256: sha256(result.value.patch), patchBytes: result.value.patch.length, receiptSha256: sha256(result.value.receiptBytes), receiptBytes: result.value.receiptBytes.length, packsAfterSha256: sha256(result.value.packsAfter), packsAfterBytes: result.value.packsAfter.length, receipt: result.value.receipt }, null, 2)); return 0; }
const invokedPath = process.argv[1]; if (invokedPath !== undefined && resolve(invokedPath) === fileURLToPath(import.meta.url)) main().then((code) => { process.exitCode = code; });
